# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(blank=True, max_length=32, verbose_name='描述')),
                ('hip', models.GenericIPAddressField(verbose_name='IPadd')),
                ('hcpu', models.CharField(max_length=8, verbose_name='cpu')),
                ('hdisk', models.CharField(max_length=16, verbose_name='磁盘')),
                ('huser', models.CharField(max_length=128, verbose_name='用户信息')),
                ('hlog', models.TextField(max_length=10240, verbose_name='日志')),
            ],
            options={
                'verbose_name': '主机信息',
                'verbose_name_plural': '主机信息',
            },
        ),
    ]
